/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.data.Data;
import controller.operations.ObjectFinder;
import controller.operations.userOperations.UserOperations;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author Ege
 */
public class AllUsersFrame extends javax.swing.JFrame {
    User user;

    /**
     * Creates new form AllUsersFramee
     */
    public AllUsersFrame(User user) {
        
        this.user=user;
        initComponents();
        showMessage.setText("");
        showMessage.setText("");
        fillUserTable();
    }
    private void fillUserTable(){
        DefaultTableModel model=(DefaultTableModel) usersTable.getModel();

        for(User u:Data.users.getUsers()){
            if(!u.getUserName().equals(user.getUserName())){
                int followers;
                int following;
                int collection;

                followers=u.getFollowers().size();


                following=u.getFollowing().size();


                collection=u.getCollectionContent().size();


                Object[] users={u.getUserName(),followers,following,collection};
                model.addRow(users);
            }

        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        followButton = new javax.swing.JButton();
        unfollowButton = new javax.swing.JButton();
        viewProfileButton = new javax.swing.JButton();
        backToUserFrame = new javax.swing.JButton();
        showMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Number of Followers", "Number of Following", "Number of Collection"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        unfollowButton.setText("Unfollow");
        unfollowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfollowButtonActionPerformed(evt);
            }
        });

        viewProfileButton.setText("View Profile");
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });

        backToUserFrame.setIcon(new javax.swing.ImageIcon("backButton.jpeg")); // NOI18N
        backToUserFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToUserFrameActionPerformed(evt);
            }
        });

        showMessage.setText("message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(backToUserFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(unfollowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(followButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backToUserFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(followButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unfollowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        showMessage.setText("");
    }//GEN-LAST:event_usersTableMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       showMessage.setText("");
    }//GEN-LAST:event_formMouseClicked

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
       DefaultTableModel model=(DefaultTableModel) usersTable.getModel();
        int selectedRow=usersTable.getSelectedRow();

        if(selectedRow==-1){
            if(usersTable.getRowCount()==0){
                showMessage.setText("User table is empty");

            }else{
                showMessage.setText("No user selected!");
            }
        }
        else{
            String username=(String) model.getValueAt(selectedRow,0);
            User selectedUser=ObjectFinder.getUserFromName(username);

            UserOperations userOperations=new UserOperations();
            if(userOperations.follow(user, username)){
                this.user=ObjectFinder.getUserFromName(user.getUserName());
                showMessage.setForeground(Color.MAGENTA);
                showMessage.setText("You followed "+username);
                model.setValueAt(selectedUser.getFollowers().size(),selectedRow, 1);
            }else{
                showMessage.setForeground(Color.red);
                showMessage.setText("You already followed "+username);
            }



        }
    }//GEN-LAST:event_followButtonActionPerformed

    private void unfollowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfollowButtonActionPerformed
       DefaultTableModel model=(DefaultTableModel) usersTable.getModel();
        int selectedRow=usersTable.getSelectedRow();

        if(selectedRow==-1){
            if(usersTable.getRowCount()==0){
                showMessage.setText("User table is empty");

            }else{
                showMessage.setText("No user selected!");
            }
        }
        else{
            String username=(String) model.getValueAt(selectedRow,0);
            User selectedUser=ObjectFinder.getUserFromName(username);

            UserOperations userOperations=new UserOperations();
            if(userOperations.unFollow(user, username)){
                this.user=ObjectFinder.getUserFromName(user.getUserName());
                showMessage.setForeground(Color.MAGENTA);
                showMessage.setText("You unfollowed "+username);
                model.setValueAt(selectedUser.getFollowers().size(),selectedRow, 1);


            }else{
                showMessage.setForeground(Color.red);
                showMessage.setText("You are not following "+username);
            }



        }
    }//GEN-LAST:event_unfollowButtonActionPerformed

    private void backToUserFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToUserFrameActionPerformed
        this.setVisible(false);
        UserFrame userFrame=new UserFrame(user);
        userFrame.setVisible(true);
    }//GEN-LAST:event_backToUserFrameActionPerformed

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
        int selectedRow=usersTable.getSelectedRow();

        if(selectedRow==-1){
            showMessage.setForeground(Color.MAGENTA);
            if(usersTable.getRowCount()==0){
                showMessage.setText("User table is empty");

            }else{
                showMessage.setText("No user selected to view profile!");
            }
    }//GEN-LAST:event_viewProfileButtonActionPerformed
        else{
            String selectedUserName=(String) usersTable.getValueAt(selectedRow,0);
            User userToVisit=ObjectFinder.getUserFromName(selectedUserName);
            ViewProfile viewProfile=new ViewProfile(user,userToVisit);
            this.setVisible(false);
            viewProfile.setVisible(true);
        }
    } 
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToUserFrame;
    private javax.swing.JButton followButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel showMessage;
    private javax.swing.JButton unfollowButton;
    private javax.swing.JTable usersTable;
    private javax.swing.JButton viewProfileButton;
    // End of variables declaration//GEN-END:variables
}
