/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.operations.ObjectFinder;
import controller.operations.fileOperations.FileUpdate;
import controller.operations.fileOperations.jsonOperations.JsonWrite;
import controller.operations.fileOperations.xmlOperations.XmlWrite;
import model.User;

/**
 *
 * @author Ege
 */
public class UserFrame extends javax.swing.JFrame {
    User user;

    /**
     * Creates new form UserFrame
     * @param
     */
    public UserFrame(User user) {
        this.user=user;
        initComponents();
        userNameMessage.setText(user.getUserName().toUpperCase()+"'s PROFILE");
        displayProfileInfo();
    }
    private void displayProfileInfo(){

        String followerNumber=String.valueOf(user.getFollowers().size());
        String followingNumber=String.valueOf(user.getFollowing().size());
        String collectionNumber=String.valueOf(user.getCollectionContent().size());
        this.numberOfFollowers.setText(followerNumber);
        this.numberOfFollowing.setText(followingNumber);
        this.numberOfCollection.setText(collectionNumber);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameMessage = new javax.swing.JLabel();
        goToFollowersFrame = new javax.swing.JButton();
        goToFollowingFrame = new javax.swing.JButton();
        goToMyCollectionFrame = new javax.swing.JButton();
        FollowersLabel = new javax.swing.JLabel();
        followingLabel = new javax.swing.JLabel();
        collectionLabel = new javax.swing.JLabel();
        numberOfFollowers = new javax.swing.JLabel();
        numberOfFollowing = new javax.swing.JLabel();
        numberOfCollection = new javax.swing.JLabel();
        goToPlatformTrendFrame = new javax.swing.JButton();
        goToAllOutfitFrame = new javax.swing.JButton();
        goToSeeAllUsersFrame = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Outfit Rating Platform");
        setResizable(false);

        userNameMessage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userNameMessage.setText("User Name:Ege");

        goToFollowersFrame.setText("Followers");
        goToFollowersFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFollowersFrameActionPerformed(evt);
            }
        });

        goToFollowingFrame.setText("Following");
        goToFollowingFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFollowingFrameActionPerformed(evt);
            }
        });

        goToMyCollectionFrame.setBackground(new java.awt.Color(153, 255, 51));
        goToMyCollectionFrame.setForeground(new java.awt.Color(51, 51, 51));
        goToMyCollectionFrame.setText("My Collections");
        goToMyCollectionFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToMyCollectionFrameActionPerformed(evt);
            }
        });

        FollowersLabel.setText("Followers");

        followingLabel.setText("Following");

        collectionLabel.setText("Collection");

        numberOfFollowers.setText("13");

        numberOfFollowing.setText("12");

        numberOfCollection.setText("3");

        goToPlatformTrendFrame.setText("Platform Trend");
        goToPlatformTrendFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToPlatformTrendFrameActionPerformed(evt);
            }
        });

        goToAllOutfitFrame.setBackground(new java.awt.Color(153, 255, 102));
        goToAllOutfitFrame.setText("See All Outfit");
        goToAllOutfitFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAllOutfitFrameActionPerformed(evt);
            }
        });

        goToSeeAllUsersFrame.setText("See All Users");
        goToSeeAllUsersFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSeeAllUsersFrameActionPerformed(evt);
            }
        });

        logOutButton.setText("Logout");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userNameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FollowersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfFollowers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(followingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfFollowing, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(283, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(goToSeeAllUsersFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goToAllOutfitFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goToPlatformTrendFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(goToFollowersFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goToFollowingFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goToMyCollectionFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numberOfFollowers, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FollowersLabel)
                                    .addComponent(followingLabel)
                                    .addComponent(collectionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberOfFollowing, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(122, 122, 122)
                .addComponent(goToFollowersFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(goToFollowingFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(goToMyCollectionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goToPlatformTrendFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goToAllOutfitFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goToSeeAllUsersFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(goToFollowersFrame);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToFollowersFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFollowersFrameActionPerformed
       this.setVisible(false);
       FollowersUsersFrame followersUsersFrame=new view.FollowersUsersFrame(user);
       followersUsersFrame.setVisible(true);
    }//GEN-LAST:event_goToFollowersFrameActionPerformed



    private void goToAllOutfitFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAllOutfitFrameActionPerformed
        this.setVisible(false);
        AllOutfitFrame allOutfitFrame=new AllOutfitFrame(user);
        allOutfitFrame.setVisible(true);
    }//GEN-LAST:event_goToAllOutfitFrameActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        FileUpdate.updateFile();
        this.setVisible(false);
        LoginFrame loginFrame=new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void goToSeeAllUsersFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSeeAllUsersFrameActionPerformed
        this.setVisible(false);
        AllUsersFrame allUsersFrame=new AllUsersFrame(user);
        allUsersFrame.setVisible(true);
    }//GEN-LAST:event_goToSeeAllUsersFrameActionPerformed

    private void goToFollowingFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFollowingFrameActionPerformed
       this.setVisible(false);
       FollowingUsersFrame followingUsersFrame=new FollowingUsersFrame(user);
       followingUsersFrame.setVisible(true);
    }//GEN-LAST:event_goToFollowingFrameActionPerformed

    private void goToPlatformTrendFrameActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        StatisticsFrame statisticsFrame=new StatisticsFrame(user);
        statisticsFrame.setVisible(true);
    }

    private void goToMyCollectionFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToMyCollectionFrameActionPerformed
        this.setVisible(false);
        MyCollectionFrame myCollectionFrame=new MyCollectionFrame(user);
        myCollectionFrame.setVisible(true);
    }//GEN-LAST:event_goToMyCollectionFrameActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FollowersLabel;
    private javax.swing.JLabel collectionLabel;
    private javax.swing.JLabel followingLabel;
    private javax.swing.JButton goToAllOutfitFrame;
    public javax.swing.JButton goToFollowersFrame;
    public javax.swing.JButton goToFollowingFrame;
    private javax.swing.JButton goToMyCollectionFrame;
    private javax.swing.JButton goToPlatformTrendFrame;
    private javax.swing.JButton goToSeeAllUsersFrame;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel numberOfCollection;
    private javax.swing.JLabel numberOfFollowers;
    private javax.swing.JLabel numberOfFollowing;
    private javax.swing.JLabel userNameMessage;
    // End of variables declaration//GEN-END:variables
}
