/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.operations.ObjectFinder;
import controller.operations.userOperations.UserOperations;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

import model.Collection;
import model.User;
import model.outfitFields.Outfit;

/**
 * @author Ege
 */
public class ViewProfile extends javax.swing.JFrame {
    User visitor;
    User owner;

    /**
     * Creates new form ViewProfile
     */
    public ViewProfile(User visitor, User owner) {
        this.visitor = visitor;
        this.owner = owner;
        initComponents();
        showMessage.setText("");
        showMessage.setForeground(Color.MAGENTA);
        profileOwnerName.setText(owner.getUserName() + "'s PROFILE");
        collectionNames.setText(owner.getUserName() + "'s Collections");
        fillCollectionBox();
        displayProfileInfo();
    }

    private void displayProfileInfo() {
        String followerNumber = String.valueOf(owner.getFollowers().size());
        String followingNumber = String.valueOf(owner.getFollowing().size());
        String collectionNumber = String.valueOf(owner.getCollectionContent().size());
        numberOfFollowersLabel.setText(followerNumber);
        numberOfFollowingLabel.setText(followingNumber);
        numberOfCollectionLabel.setText(collectionNumber);
    }

    private void fillCollectionBox() {
        if (owner.getCollectionContent().size() != 0) {
            for (String id : owner.getCollectionContent()) {
                String colName = ObjectFinder.getCollectionFromCollectionId(id).getCollectionName();
                allCollections.addItem(id + "," + colName);
            }
        }
    }

    private void fillCollectionOutfitsTable(Collection collection) {
        DefaultTableModel model = (DefaultTableModel) outfitsOfCollectionTable.getModel();
        for (String outfit : collection.getCollectionOutfits()) {
            Outfit o = ObjectFinder.getOutfitFromProductId(outfit);
            Object[] outfitItem = {o.getProductId(), o.getBrandName(), o.getColor(),
                    o.getClothingType(), o.getSize(), o.getGender(), o.getLikedUsers().size(), o.getDislikedUsers().size()};
            model.addRow(outfitItem);

        }


    }

    private void removeRows() {
        DefaultTableModel model = (DefaultTableModel) outfitsOfCollectionTable.getModel();
        int row = 0;
        while (model.getRowCount() > 0) {
            model.removeRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        profileOwnerName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberOfFollowersLabel = new javax.swing.JLabel();
        numberOfFollowingLabel = new javax.swing.JLabel();
        numberOfCollectionLabel = new javax.swing.JLabel();
        allCollections = new javax.swing.JComboBox<>();
        followButton = new javax.swing.JButton();
        unfollowButton = new javax.swing.JButton();
        collectionNames = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outfitsOfCollectionTable = new javax.swing.JTable();
        showCollectionName = new javax.swing.JLabel();
        showMessage = new javax.swing.JLabel();
        backHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profileOwnerName.setText("EGE'S PROFILE");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Followers");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Following");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Collections");

        numberOfFollowersLabel.setText("jLabel4");

        numberOfFollowingLabel.setText("jLabel5");

        numberOfCollectionLabel.setText("jLabel6");

        allCollections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCollectionsActionPerformed(evt);
            }
        });

        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        unfollowButton.setText("Unfollow");
        unfollowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfollowButtonActionPerformed(evt);
            }
        });

        collectionNames.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        collectionNames.setText("EGE'S COLLECTION");

        outfitsOfCollectionTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Product ID", "Brand Name", "Color", "Clothing Type", "Size", "Gender", "Number of Likes", "Number of Dislikes"
                }
        ));
        jScrollPane1.setViewportView(outfitsOfCollectionTable);

        showCollectionName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showCollectionName.setForeground(new java.awt.Color(51, 51, 255));
        showCollectionName.setText("Collection Name");

        showMessage.setText("jLabel5");

        backHomeButton.setIcon(new javax.swing.ImageIcon("backButton.jpeg")); // NOI18N
        backHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(allCollections, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(collectionNames, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(profileOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(showCollectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(backHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberOfFollowingLabel))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberOfCollectionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(followButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(unfollowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(numberOfFollowersLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(numberOfFollowersLabel)
                                                        .addComponent(numberOfFollowingLabel)
                                                        .addComponent(numberOfCollectionLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(unfollowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(followButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(backHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(profileOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(collectionNames, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(allCollections, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(showCollectionName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {
        UserOperations userOperations = new UserOperations();
        if (userOperations.follow(visitor, owner.getUserName())) {
            this.owner = ObjectFinder.getUserFromName(owner.getUserName());
            this.visitor = ObjectFinder.getUserFromName(visitor.getUserName());
            showMessage.setForeground(Color.MAGENTA);
            showMessage.setText("Followed " + owner.getUserName());
            numberOfFollowersLabel.setText(String.valueOf(owner.getFollowers().size()));

        } else {
            showMessage.setForeground(Color.red);
            showMessage.setText("You already followed " + owner.getUserName());
        }
    }


    private void allCollectionsActionPerformed(java.awt.event.ActionEvent evt) {
        removeRows();
        if (allCollections.getSelectedIndex() != -1) {
            String selectedCollectionName = (String) allCollections.getSelectedItem();
            Collection targetCollection = ObjectFinder.getCollectionFromCollectionId(MyCollectionFrame.getId(selectedCollectionName));
            showCollectionName.setText("COLLECTION NAME: " + targetCollection.getCollectionName());
            fillCollectionOutfitsTable(targetCollection);

        }
    }


    private void unfollowButtonActionPerformed(java.awt.event.ActionEvent evt) {
        UserOperations userOperations = new UserOperations();
        if (userOperations.unFollow(visitor, owner.getUserName())) {
            this.owner = ObjectFinder.getUserFromName(owner.getUserName());
            this.visitor = ObjectFinder.getUserFromName(visitor.getUserName());
            showMessage.setForeground(Color.GREEN);
            showMessage.setText("You unfollowed " + owner.getUserName());
            numberOfFollowersLabel.setText(String.valueOf(owner.getFollowers().size()));

        } else {
            showMessage.setForeground(Color.red);
            showMessage.setText("You are not following " + owner.getUserName());
        }
    }

    private void backHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        UserFrame userFrame = new UserFrame(visitor);
        userFrame.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> allCollections;
    private javax.swing.JButton backHomeButton;
    private javax.swing.JLabel collectionNames;
    private javax.swing.JButton followButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberOfCollectionLabel;
    private javax.swing.JLabel numberOfFollowersLabel;
    private javax.swing.JLabel numberOfFollowingLabel;
    private javax.swing.JTable outfitsOfCollectionTable;
    private javax.swing.JLabel profileOwnerName;
    private javax.swing.JLabel showCollectionName;
    private javax.swing.JLabel showMessage;
    private javax.swing.JButton unfollowButton;
    // End of variables declaration


}